import { ICritter } from "@/types";

export const mockCritters: ICritter[] = [
  {
    id: 1,
    name: '아쿠아핀',
    level: 5,
    description: '물을 다루는 신비한 크리터. 파도가 그의 친구다.',
    emoji: '💧',
    imageUrl: '/critters/no-image.png',
    type: 'water',
    baseHp: 45,
    baseAttack: 49,
    baseDefense: 49,
    hpGrowth: 1.1,
    attackGrowth: 1.1,
    defenseGrowth: 1.1,
  },
  {
    id: 2,
    name: '플레임퍼',
    level: 3,
    description: '뜨거운 불꽃을 내뿜는 크리터. 성격이 급한 편이다.',
    emoji: '🔥',
    imageUrl: '/critters/no-image.png',
    type: 'fire',
    baseHp: 39,
    baseAttack: 52,
    baseDefense: 43,
    hpGrowth: 1.1,
    attackGrowth: 1.1,
    defenseGrowth: 1.1,
  },
  {
    id: 3,
    name: '리프링',
    level: 8,
    description: '숲의 기운을 받은 풀잎 크리터. 햇살을 받으면 강해진다.',
    emoji: '🌿',
    imageUrl: '/critters/no-image.png',
    type: 'grass',
    baseHp: 60,
    baseAttack: 62,
    baseDefense: 63,
    hpGrowth: 1.1,
    attackGrowth: 1.1,
    defenseGrowth: 1.1,
  },
]; 